// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: videos.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createVideo = `-- name: CreateVideo :one
INSERT INTO videos (id, created_at, updated_at, lift_type, user_id)
VALUES (
	gen_random_uuid(),
	NOW(),
	NOW(),
	$1,
	$2
)
RETURNING id, created_at, updated_at, user_id, lift_type
`

type CreateVideoParams struct {
	LiftType string
	UserID   uuid.UUID
}

func (q *Queries) CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error) {
	row := q.db.QueryRowContext(ctx, createVideo, arg.LiftType, arg.UserID)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.LiftType,
	)
	return i, err
}

const deleteVideoById = `-- name: DeleteVideoById :exec
DELETE
FROM videos
where id = $1
`

func (q *Queries) DeleteVideoById(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteVideoById, id)
	return err
}

const deleteVideos = `-- name: DeleteVideos :exec
DELETE
FROM videos
`

func (q *Queries) DeleteVideos(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteVideos)
	return err
}

const getSingleUserVideos = `-- name: GetSingleUserVideos :many
SELECT id, created_at, updated_at, user_id, lift_type
FROM videos
WHERE user_id = $1
ORDER BY created_at desc
`

func (q *Queries) GetSingleUserVideos(ctx context.Context, userID uuid.UUID) ([]Video, error) {
	rows, err := q.db.QueryContext(ctx, getSingleUserVideos, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.LiftType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVideo = `-- name: GetVideo :one
SELECT id, created_at, updated_at, user_id, lift_type
FROM videos
WHERE id = $1
`

func (q *Queries) GetVideo(ctx context.Context, id uuid.UUID) (Video, error) {
	row := q.db.QueryRowContext(ctx, getVideo, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.LiftType,
	)
	return i, err
}
